# Change these first
owner: traqy # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: TechinAsia
    url: https://www.techinasia.com
  - name: TechinAsia_WordPress_API
    url: https://www.techinasia.com/wp-json/techinasia/2.0/posts
  - name: TechinAsia_Laravel_API
    url: https://www.techinasia.com/api/2.0/companies
  - name: TechinAsia_Conference
    url: https://conference.techinasia.com
  - name: TechinAsia_PDC
    url: https://pdc.techinasia.com
  - name: TechinAsia_Advertise
    url: https://advertise.techinasia.com
  - name: TechinAsia_Sync
    url: https://sync.techinasia.com
  - name: TechinAsia_AWS
    url: https://aws.techinasia.com
  - name: TechinAsia_Saigon
    url: https://saigon.techinasia.com


